from PIL import Image , ImageEnhance , ImageFilter , ImageOps
import matplotlib.pyplot as plt 
import os
"""
## Partie 1
os.makedirs("results", exist_ok=True)

img = Image.open("image.jpg")

plt.figure()
plt.subplot(111)
plt.imshow(img)
plt.axis("off")

img.save("results/image_originale.png")

## Partie 2
os.makedirs("results",exist_ok=True)
image= Image.open("image.jpg")
image_resize= image.resize((300,150))
plt.figure(figsize=(8,4))
plt.subplot(1,2,1)
plt.imshow(image)
plt.axis("off")
plt.title("Image originale")

plt.subplot(1,2,2)
plt.imshow(image_resize)
plt.axis("off")
plt.title("image redimensionnee")

image_resize.save("results/image_redimensionnee.png")

plt.show()

## Partie 3
os.makedirs("results",exist_ok=True)
image= Image.open("image.jpg")
enhance = ImageEnhance.Brightness(image)
augmente= enhance.enhance(1.5)
plt.figure(figsize=(8,4))
plt.subplot(1,2,1)
plt.imshow(image)
plt.axis("off")
plt.title("Image originale")
plt.subplot(1,2,2)
plt.imshow(augmente)
plt.axis("off")
plt.title("image avec luminosite augmentee")
augmente.save("results/image_luminosite_augmente.png")
plt.show()

## Partie 4
os.makedirs("results",exist_ok=True)
image= Image.open("image.jpg")
image_gray= image.convert("L")
plt.figure(figsize=(8,4))
plt.subplot(1,2,1)
plt.imshow(image)
plt.axis("off")
plt.title("Image originale")
plt.subplot(1,2,2)
plt.imshow(image_gray,cmap="gray")
plt.axis("off")
plt.title("image gris")
image_gray.save("results/image_niveaux_de_gris.png")

plt.show()

## Partie 5
os.makedirs("results",exist_ok=True)
image= Image.open("image.jpg")
image_gray= image.convert("L")
t= 128
image_binaire= image_gray.point(lambda p: 255 if p > t else 0)
plt.figure(figsize=(8,4))
plt.subplot(1,2,1)
plt.imshow(image_gray,cmap="gray")
plt.axis("off")
plt.title("Image grise")
plt.subplot(1,2,2)
plt.imshow(image_binaire,cmap="gray")
plt.axis("off") 
plt.title("image binaire")
image_binaire.save("results/image_binaire.png")
plt.show()

## Partie 6
os.makedirs("results",exist_ok=True)
image= Image.open("image.jpg")
image_gray= image.convert("L")
image_contour=image_gray.filter(ImageFilter.FIND_EDGES)
plt.figure(figsize=(8,4))
plt.subplot(1,2,1)
plt.imshow(image_gray,cmap="gray")
plt.axis("off")
plt.title("Image grise")
plt.subplot(1,2,2)
plt.imshow(image_contour,cmap="gray")
plt.axis("off")
plt.title("image contour")
image_contour.save("results/image_contour.png")
plt.show()

### Partie 7
os.makedirs("results",exist_ok=True)
image= Image.open("image.jpg")
filter1= image.filter(ImageFilter.GaussianBlur(radius=3))
filter2= image.filter(ImageFilter.GaussianBlur(radius=4))
filter3= image.filter(ImageFilter.GaussianBlur(radius=5))
plt.figure(figsize=(12,6))
plt.subplot(1,4,1)
plt.imshow(image)
plt.axis("off")
plt.title("Image originale")
plt.subplot(1,4,2)
plt.imshow(filter1)
plt.axis("off") 
plt.title(" flou gaussien (radius=1)")
plt.subplot(1,4,3)
plt.imshow(filter2)
plt.axis("off")
plt.title("flou gaussien (radius=2)")
plt.subplot(1,4,4)
plt.imshow(filter3)
plt.axis("off")
plt.title(" flou gaussien (radius=3)")

filter1.save("results/image_flou_gaussien_radius_1.png")
filter2.save("results/image_flou_gaussien_radius_2.png")
filter3.save("results/image_flou_gaussien_radius_3.png")
plt.show()

### Partie 8
os.makedirs("results",exist_ok=True)    
image= Image.open("image.jpg")
image_gray= image.convert("L")
histogramme= image_gray.histogram()
plt.figure(figsize=(8,4))
plt.plot(histogramme)
plt.title("Histogramme de l'image en niveaux de gris")
plt.xlabel("Niveaux de gris")
plt.ylabel("Nombre de pixels")
plt.show()
"""
## Partie 9
os.makedirs("results",exist_ok=True)
image= Image.open("image.jpg")
image_gray= image.convert("L")
image_egalisee= ImageOps.equalize(image_gray)
plt.figure(figsize=(8,4))
plt.subplot(1,2,1)
plt.imshow(image_gray,cmap="gray")
plt.axis("off")
plt.title("Image avant egalisation")
plt.subplot(1,2,2)
plt.imshow(image_egalisee,cmap="gray")
plt.axis("off")
plt.title("image egalisee")
image_egalisee.save("results/image_egalisee.png")
plt.show()
